version: "3"

services:
  expo-srv:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: leopays/expo-srv:latest
    deploy:
      restart_policy:
        condition: on-failure
    env_file: .env
    #environment:
    #  REPO: "https://github.com/org/expo-app.git"
    #  BRANCH: "master"
    #  USERNAME: "user"
    #  PASSWORD: "pswd"
    #  REACT_NATIVE_PACKAGER_HOSTNAME: "192.168.1.1"
    #  GIT_PULL_INTERVAL: 5
    #  VERBOSE: false
    #  WEB: true
    ports:
      - "19000:19000"
      - "19001:19001"
      #- "19002:19002"
      - "19006:19006"
    expose:
      - "19000"
      - "19001"
      #- "19002"
      - "19006"
