version: "3"

services:
  expo-srv:
    #build:
    #  context: ../
    #  dockerfile: ./docker/Dockerfile
    image: leopays/expo-srv:latest
    deploy:
      restart_policy:
        condition: on-failure
    env_file: .env
    #environment:
    #  NODE_ENV: "production"
    #  DATA_DIR: "/data"
    #  REPO: "https://github.com/org/expo-app.git"
    #  BRANCH: "master"
    #  USERNAME: "user"
    #  PASSWORD: "pswd"
    #  REACT_NATIVE_PACKAGER_HOSTNAME: "127.0.0.1"
    #  GIT_PULL_INTERVAL: 30
    #  VERBOSE: false
    #  WEB: true
    #  HTTPS: true
    #  SSL_CRT_FILE: "cert.pem"
    #  SSL_KEY_FILE: "privkey.pem"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    expose:
      - "19000"
      - "19001"
      - "19002"
      - "19006"
    volumes:
      - "../../data/expo-srv:/data"
      #- "../data/expo-srv:/data"
